# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

images:
  jenkinsmaster: "gcr.io/sds-readiness/jenkinsmaster:latest"
  jenkinsagent: "gcr.io/sds-readiness/jenkinsagent:latest"
  jenkinsgradle: "gcr.io/sds-readiness/jenkinsgradle:prod"
  jenkinsshelldev: "gcr.io/sds-readiness/jenkinsshelldev:prod"

# github, jenkins or ldap
adminEmail: "me@email.com"
adminPassword: "admin"
adminUser: "admin"
javaOptions: "-Xms1024m -Xmx1024m -Djenkins.install.runSetupWizard=false"
jenkinsHookUrl:
jenkinsUrl: "jenkins.somedomain.io"
jobsRepo: "URL to jobs repo"
seedJobToken: "seed"

# github, jenkins or ldap
security: "jenkins"
adminUserSalt: "change me if using jenkins security"

slack:
  slackDomain: "samsung-cnct"
  slackRoom: "#ping-jenkins"
  slackApiToken: "change me"

github:
  githubClientId: "change me"
  githubAccessToken: "change me"
  githubUserName: "change me"
  githubOrgNames: "change me"
  githubClientKey: "change me"
  admin_usernames: "change me"

gke:
  clusterName: "production-cluster"
  clusterPrimaryZone: "us-east1-b"
  gkeProject: "change me"
  svcAccountId: "change me"
  svcAccountKey: "change me"

ssh:
  sshPrivateKey: "change me"
  sshPublicKey: "change me"

# Storageclass must be pre provisioned on the Kubernetes cluster prior to installing jenkins
persistence:
  claimName: "jenkins-jobs"
  component: "data_volume"
  enabled: true
  storageClass: "standard"
  reclaiming: "Retained"
  accessMode: "ReadWriteOnce"
  size: 10Gi

ldap:
  ldapServer:
  rootDN:
  userSearchBase:
  userSearchFilter: "uid={0}"
  groupMembershipFilter:
  managerDN:
  managerDNPassword: "change me"

agent:
  cpu: "200m"
  memory: "1024Mi"
  port: 50000
  requestsPerHost: 100

master:
  cpu: "200m"
  memory: "1024Mi"
  port: 8080
  serviceType: "NodePort"

helm:
  svcAccountId: "change me"
  svcAccountKey: "change me"
